# Generated by Django 3.2.11 on 2022-06-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('date_of_birth', models.DateField(max_length=20)),
                ('time_of_birth', models.CharField(max_length=250)),
                ('birth_city_sate', models.CharField(max_length=250)),
                ('longitude', models.CharField(max_length=250)),
                ('lattitude', models.CharField(max_length=250)),
                ('your_current_location', models.CharField(max_length=250)),
                ('transits_chart_date', models.DateField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('cell_number', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RateyourReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('rate_synchronic', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
